// ── Default Chart of Accounts for Romaa Construction ERP (India) ─────────────
//
// Standard COA with 60+ accounts covering:
//   - Assets (Current + Fixed + ITC/Tax recoverable)
//   - Liabilities (Vendor/Contractor payables, GST payable, TDS payable)
//   - Equity (Capital, Retained Earnings)
//   - Income (Project revenue, Other income)
//   - Expenses (Material, Labour, Site overheads, Admin, Financial, Depreciation)
//
// Code convention:
//   1000–1999  Assets
//   2000–2999  Liabilities
//   3000–3999  Equity
//   4000–4999  Income
//   5000–5999  Expenses
//
// is_system: true  → seeded by system, cannot be deleted
// is_group:  true  → parent/summary node, no direct postings
// level:     0     → root header (Assets, Liabilities, etc.)
//            1     → sub-group  (Current Assets, Tax Liabilities, etc.)
//            2     → standard leaf account

const DEFAULT_ACCOUNTS = [

  // ╔══════════════════════════════════════════════════════════════╗
  // ║  1000 — ASSETS                                               ║
  // ╚══════════════════════════════════════════════════════════════╝

  {
    account_code:    "1000",
    account_name:    "Assets",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     null,
    level:           0,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Root — all company assets",
  },

  // ── Current Assets ────────────────────────────────────────────────────────
  {
    account_code:    "1001",
    account_name:    "Current Assets",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Cash, bank, receivables, advances, inventory",
  },
  {
    account_code:    "1010",
    account_name:    "Cash / Petty Cash",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_bank_cash:    true,
    is_system:       true,
    description:     "Physical cash on hand — petty cash box",
  },
  {
    account_code:    "1020",
    account_name:    "Bank Accounts",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_bank_cash:    true,
    is_system:       true,
    description:     "All company bank accounts — add sub-accounts per bank",
  },
  {
    account_code:    "1020-001",
    account_name:    "Primary Bank Account",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1020",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_bank_cash:    true,
    is_system:       true,
    description:     "Main operating bank account — update name with actual bank",
  },
  {
    account_code:    "1030",
    account_name:    "Advances & Deposits",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Advances paid to vendors/contractors, EMD, security deposits",
  },
  {
    account_code:    "1030-ADV-V",
    account_name:    "Advances to Vendors",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1030",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Advance payments made to material suppliers before bill is raised",
  },
  {
    account_code:    "1030-ADV-C",
    account_name:    "Advances to Contractors",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1030",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Advance payments made to contractors before work bill is raised",
  },
  {
    account_code:    "1030-EMD",
    account_name:    "Earnest Money Deposit (EMD)",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1030",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "EMD paid for tenders — refundable on tender completion or rejection",
  },
  {
    account_code:    "1030-SD",
    account_name:    "Security Deposit (Paid)",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1030",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Security deposits paid to clients or government authorities",
  },
  {
    account_code:    "1040",
    account_name:    "Material at Site (Inventory)",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Stock of materials physically held at site — cement, steel, aggregates, etc.",
  },
  {
    account_code:    "1050",
    account_name:    "Receivables from Clients",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Amounts due from clients against raised client bills — add sub-ledger per client",
  },
  {
    account_code:    "1060",
    account_name:    "Retention Money Receivable",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Retention money held by clients — released after DLP completion",
  },
  {
    account_code:    "1070",
    account_name:    "TDS Receivable",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "TDS",
    is_system:       true,
    description:     "TDS deducted by clients from payments (Form 26AS credit — refundable or adjustable)",
  },

  // ── GST Input Tax Credit (ITC) ────────────────────────────────────────────
  // These are technically a reduction of tax liability (or a current asset)
  {
    account_code:    "1080",
    account_name:    "GST Input Tax Credit (ITC)",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1001",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "GST recoverable input credits — offset against GST output payable",
  },
  {
    account_code:    "1080-CGST",
    account_name:    "CGST Input (ITC)",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1080",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "CGST_Input",
    is_system:       true,
    description:     "Central GST input tax credit — recorded when purchase bill is raised (intra-state)",
  },
  {
    account_code:    "1080-SGST",
    account_name:    "SGST Input (ITC)",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1080",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "SGST_Input",
    is_system:       true,
    description:     "State GST input tax credit — recorded when purchase bill is raised (intra-state)",
  },
  {
    account_code:    "1080-IGST",
    account_name:    "IGST Input (ITC)",
    account_type:    "Asset",
    account_subtype: "Current Asset",
    normal_balance:  "Dr",
    parent_code:     "1080",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "IGST_Input",
    is_system:       true,
    description:     "Integrated GST input tax credit — recorded on inter-state purchases",
  },

  // ── Fixed Assets ──────────────────────────────────────────────────────────
  {
    account_code:    "1100",
    account_name:    "Fixed Assets",
    account_type:    "Asset",
    account_subtype: "Fixed Asset",
    normal_balance:  "Dr",
    parent_code:     "1000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Long-term tangible assets — machinery, equipment, vehicles",
  },
  {
    account_code:    "1110",
    account_name:    "Plant & Machinery",
    account_type:    "Asset",
    account_subtype: "Fixed Asset",
    normal_balance:  "Dr",
    parent_code:     "1100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Heavy machinery — JCB, concrete mixer, cranes, batching plant (at cost)",
  },
  {
    account_code:    "1110-DEP",
    account_name:    "Accumulated Depreciation — Plant & Machinery",
    account_type:    "Asset",
    account_subtype: "Contra Asset",
    normal_balance:  "Cr",
    parent_code:     "1100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Contra asset — accumulated depreciation on P&M. Net book value = 1110 − 1110-DEP",
  },
  {
    account_code:    "1120",
    account_name:    "Equipment & Tools",
    account_type:    "Asset",
    account_subtype: "Fixed Asset",
    normal_balance:  "Dr",
    parent_code:     "1100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Small equipment, power tools, scaffolding, survey instruments",
  },
  {
    account_code:    "1130",
    account_name:    "Vehicles",
    account_type:    "Asset",
    account_subtype: "Fixed Asset",
    normal_balance:  "Dr",
    parent_code:     "1100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Company-owned vehicles — pickup trucks, tippers, site jeeps",
  },
  {
    account_code:    "1140",
    account_name:    "Office Furniture & Fixtures",
    account_type:    "Asset",
    account_subtype: "Fixed Asset",
    normal_balance:  "Dr",
    parent_code:     "1100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Office computers, furniture, printers, AC units",
  },


  // ╔══════════════════════════════════════════════════════════════╗
  // ║  2000 — LIABILITIES                                          ║
  // ╚══════════════════════════════════════════════════════════════╝

  {
    account_code:    "2000",
    account_name:    "Liabilities",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     null,
    level:           0,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Root — all company liabilities",
  },

  // ── Current Liabilities ───────────────────────────────────────────────────
  {
    account_code:    "2001",
    account_name:    "Current Liabilities",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     "2000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Short-term obligations — payables, advances received, retention held",
  },
  {
    account_code:    "2010",
    account_name:    "Payables to Vendors",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     "2001",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Group — individual vendor payable sub-accounts auto-created per vendor",
  },
  {
    account_code:    "2020",
    account_name:    "Payables to Contractors",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     "2001",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Group — individual contractor payable sub-accounts auto-created per contractor",
  },
  {
    account_code:    "2030",
    account_name:    "Advances Received from Clients",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     "2001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Client mobilisation advances received — adjusted against future client bills",
  },
  {
    account_code:    "2040",
    account_name:    "Retention Money Payable (Held from Contractors)",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     "2001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Retention withheld from contractor payments — released after DLP/project completion",
  },
  {
    account_code:    "2050",
    account_name:    "Employee Payroll Payable",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     "2001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Net salaries payable to employees after PF, ESI, TDS deductions",
  },
  {
    account_code:    "2060",
    account_name:    "PF & ESI Payable",
    account_type:    "Liability",
    account_subtype: "Current Liability",
    normal_balance:  "Cr",
    parent_code:     "2001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Provident Fund (12%) and Employee State Insurance (3.25%) payable to government",
  },

  // ── Tax Liabilities ───────────────────────────────────────────────────────
  {
    account_code:    "2100",
    account_name:    "Tax Liabilities",
    account_type:    "Liability",
    account_subtype: "Tax Liability",
    normal_balance:  "Cr",
    parent_code:     "2000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "GST output payable, TDS payable, income tax provisions",
  },
  {
    account_code:    "2110",
    account_name:    "CGST Payable (Output)",
    account_type:    "Liability",
    account_subtype: "Tax Liability",
    normal_balance:  "Cr",
    parent_code:     "2100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "CGST_Output",
    is_system:       true,
    description:     "Central GST collected on client billing — net of CGST Input ITC = payable to govt",
  },
  {
    account_code:    "2120",
    account_name:    "SGST Payable (Output)",
    account_type:    "Liability",
    account_subtype: "Tax Liability",
    normal_balance:  "Cr",
    parent_code:     "2100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "SGST_Output",
    is_system:       true,
    description:     "State GST collected on client billing — net of SGST Input ITC = payable to state govt",
  },
  {
    account_code:    "2130",
    account_name:    "IGST Payable (Output)",
    account_type:    "Liability",
    account_subtype: "Tax Liability",
    normal_balance:  "Cr",
    parent_code:     "2100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "IGST_Output",
    is_system:       true,
    description:     "Integrated GST collected on inter-state client billing",
  },
  {
    account_code:    "2140",
    account_name:    "TDS Payable",
    account_type:    "Liability",
    account_subtype: "Tax Liability",
    normal_balance:  "Cr",
    parent_code:     "2100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "TDS",
    is_system:       true,
    description:     "TDS deducted at source from contractor payments (Sec 194C @ 1%). Payable to IT Dept.",
  },
  {
    account_code:    "2150",
    account_name:    "ITC Reversal (GST Reversed)",
    account_type:    "Liability",
    account_subtype: "Tax Liability",
    normal_balance:  "Cr",
    parent_code:     "2100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "ITC_Reversal",
    is_system:       true,
    description:     "ITC reversed when material is returned (Credit Note) or used for exempt supplies",
  },


  // ╔══════════════════════════════════════════════════════════════╗
  // ║  3000 — EQUITY / CAPITAL                                     ║
  // ╚══════════════════════════════════════════════════════════════╝

  {
    account_code:    "3000",
    account_name:    "Equity / Capital",
    account_type:    "Equity",
    account_subtype: "Capital",
    normal_balance:  "Cr",
    parent_code:     null,
    level:           0,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Root — owner's equity and retained earnings",
  },
  {
    account_code:    "3010",
    account_name:    "Partner / Promoter Capital",
    account_type:    "Equity",
    account_subtype: "Capital",
    normal_balance:  "Cr",
    parent_code:     "3000",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Capital contributed by partners/promoters — add sub-accounts per partner",
  },
  {
    account_code:    "3020",
    account_name:    "Retained Earnings / Reserves",
    account_type:    "Equity",
    account_subtype: "Reserves",
    normal_balance:  "Cr",
    parent_code:     "3000",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Accumulated profits retained in the business from prior years",
  },
  {
    account_code:    "3030",
    account_name:    "Current Year Profit / Loss",
    account_type:    "Equity",
    account_subtype: "Reserves",
    normal_balance:  "Cr",
    parent_code:     "3000",
    level:           2,
    is_group:        false,
    is_posting_account: false,
    is_system:       true,
    description:     "Auto-computed: total Income minus total Expenses for the current financial year",
  },


  // ╔══════════════════════════════════════════════════════════════╗
  // ║  4000 — INCOME / REVENUE                                     ║
  // ╚══════════════════════════════════════════════════════════════╝

  {
    account_code:    "4000",
    account_name:    "Income / Revenue",
    account_type:    "Income",
    account_subtype: "Operating Income",
    normal_balance:  "Cr",
    parent_code:     null,
    level:           0,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Root — all company revenue",
  },
  {
    account_code:    "4010",
    account_name:    "Project / Contract Revenue",
    account_type:    "Income",
    account_subtype: "Operating Income",
    normal_balance:  "Cr",
    parent_code:     "4000",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Revenue from client billing — construction contracts, work orders",
  },
  {
    account_code:    "4020",
    account_name:    "Equipment Hire Revenue",
    account_type:    "Income",
    account_subtype: "Operating Income",
    normal_balance:  "Cr",
    parent_code:     "4000",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Revenue from hiring out company machinery/equipment to third parties",
  },
  {
    account_code:    "4030",
    account_name:    "Penalties Recovered from Vendors",
    account_type:    "Income",
    account_subtype: "Other Income",
    normal_balance:  "Cr",
    parent_code:     "4000",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Penalty amounts recovered from vendors/contractors via Debit Notes",
  },
  {
    account_code:    "4040",
    account_name:    "Interest Received",
    account_type:    "Income",
    account_subtype: "Other Income",
    normal_balance:  "Cr",
    parent_code:     "4000",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Interest income on bank FD, savings account, or loans given to employees",
  },
  {
    account_code:    "4050",
    account_name:    "Miscellaneous Income",
    account_type:    "Income",
    account_subtype: "Other Income",
    normal_balance:  "Cr",
    parent_code:     "4000",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Any other income not classified above — scrap sales, forfeitures, etc.",
  },


  // ╔══════════════════════════════════════════════════════════════╗
  // ║  5000 — EXPENSES                                             ║
  // ╚══════════════════════════════════════════════════════════════╝

  {
    account_code:    "5000",
    account_name:    "Expenses",
    account_type:    "Expense",
    account_subtype: "Direct Cost",
    normal_balance:  "Dr",
    parent_code:     null,
    level:           0,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Root — all company expenses",
  },

  // ── Direct / Project Costs ────────────────────────────────────────────────
  {
    account_code:    "5001",
    account_name:    "Material & Labour (Direct Costs)",
    account_type:    "Expense",
    account_subtype: "Direct Cost",
    normal_balance:  "Dr",
    parent_code:     "5000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Direct project costs — materials consumed and contract labour",
  },
  {
    account_code:    "5010",
    account_name:    "Material Cost",
    account_type:    "Expense",
    account_subtype: "Direct Cost",
    normal_balance:  "Dr",
    parent_code:     "5001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Cost of materials consumed in construction — cement, steel, aggregates, admixtures",
  },
  {
    account_code:    "5020",
    account_name:    "Contract Labour Cost",
    account_type:    "Expense",
    account_subtype: "Direct Cost",
    normal_balance:  "Dr",
    parent_code:     "5001",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Group — individual contractor cost sub-accounts auto-created per contractor",
  },
  {
    account_code:    "5030",
    account_name:    "Subcontract Charges",
    account_type:    "Expense",
    account_subtype: "Direct Cost",
    normal_balance:  "Dr",
    parent_code:     "5001",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Payments for specific subcontracted work items not covered by main contractor",
  },

  // ── Site Overheads ────────────────────────────────────────────────────────
  {
    account_code:    "5100",
    account_name:    "Site Overheads",
    account_type:    "Expense",
    account_subtype: "Site Overhead",
    normal_balance:  "Dr",
    parent_code:     "5000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Indirect site running costs — transport, plant hire, fuel, site facilities",
  },
  {
    account_code:    "5110",
    account_name:    "Site Staff Salary",
    account_type:    "Expense",
    account_subtype: "Site Overhead",
    normal_balance:  "Dr",
    parent_code:     "5100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Salaries of site-based employees — site engineers, foremen, surveyors",
  },
  {
    account_code:    "5120",
    account_name:    "Transportation & Logistics",
    account_type:    "Expense",
    account_subtype: "Site Overhead",
    normal_balance:  "Dr",
    parent_code:     "5100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Fuel, vehicle hire, material transport, tipper charges",
  },
  {
    account_code:    "5130",
    account_name:    "Plant & Machinery Hire",
    account_type:    "Expense",
    account_subtype: "Site Overhead",
    normal_balance:  "Dr",
    parent_code:     "5100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Rental charges for cranes, concrete mixer, compactors, batching plant on hire",
  },
  {
    account_code:    "5140",
    account_name:    "Fuel & Power",
    account_type:    "Expense",
    account_subtype: "Site Overhead",
    normal_balance:  "Dr",
    parent_code:     "5100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Diesel for generators, electricity charges, water pump running costs",
  },
  {
    account_code:    "5150",
    account_name:    "Site Facilities & Safety",
    account_type:    "Expense",
    account_subtype: "Site Overhead",
    normal_balance:  "Dr",
    parent_code:     "5100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Temporary sheds, toilets, first-aid, safety equipment, PPE kits",
  },
  {
    account_code:    "5160",
    account_name:    "Site Contingency & Misc",
    account_type:    "Expense",
    account_subtype: "Site Overhead",
    normal_balance:  "Dr",
    parent_code:     "5100",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Unplanned site expenses not covered by other categories",
  },

  // ── Office & Admin Expenses ───────────────────────────────────────────────
  {
    account_code:    "5200",
    account_name:    "Office & Administrative Expenses",
    account_type:    "Expense",
    account_subtype: "Admin Expense",
    normal_balance:  "Dr",
    parent_code:     "5000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Head office running costs — staff, rent, utilities, supplies",
  },
  {
    account_code:    "5210",
    account_name:    "Office Staff Salary",
    account_type:    "Expense",
    account_subtype: "Admin Expense",
    normal_balance:  "Dr",
    parent_code:     "5200",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Salaries of office staff — accounts, HR, management, admin",
  },
  {
    account_code:    "5220",
    account_name:    "Office Rent",
    account_type:    "Expense",
    account_subtype: "Admin Expense",
    normal_balance:  "Dr",
    parent_code:     "5200",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Monthly rent for office premises",
  },
  {
    account_code:    "5230",
    account_name:    "Office Supplies & Stationery",
    account_type:    "Expense",
    account_subtype: "Admin Expense",
    normal_balance:  "Dr",
    parent_code:     "5200",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Paper, printing, cartridges, office consumables",
  },
  {
    account_code:    "5240",
    account_name:    "Telecom & Internet",
    account_type:    "Expense",
    account_subtype: "Admin Expense",
    normal_balance:  "Dr",
    parent_code:     "5200",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Mobile bills, internet broadband, telephone charges",
  },
  {
    account_code:    "5250",
    account_name:    "Insurance Premium",
    account_type:    "Expense",
    account_subtype: "Admin Expense",
    normal_balance:  "Dr",
    parent_code:     "5200",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Contractor All Risk (CAR), vehicle, health, and liability insurance premiums",
  },

  // ── Financial & Statutory Expenses ───────────────────────────────────────
  {
    account_code:    "5300",
    account_name:    "Financial & Statutory Expenses",
    account_type:    "Expense",
    account_subtype: "Financial Expense",
    normal_balance:  "Dr",
    parent_code:     "5000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Interest charges, bank fees, audit fees, legal fees",
  },
  {
    account_code:    "5310",
    account_name:    "Interest Paid",
    account_type:    "Expense",
    account_subtype: "Financial Expense",
    normal_balance:  "Dr",
    parent_code:     "5300",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Interest on bank OD, project loans, delayed payment interest",
  },
  {
    account_code:    "5320",
    account_name:    "Bank Charges & Commission",
    account_type:    "Expense",
    account_subtype: "Financial Expense",
    normal_balance:  "Dr",
    parent_code:     "5300",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Bank transaction charges, cheque bounce fees, NEFT/RTGS charges",
  },
  {
    account_code:    "5330",
    account_name:    "Audit & Professional Fees",
    account_type:    "Expense",
    account_subtype: "Financial Expense",
    normal_balance:  "Dr",
    parent_code:     "5300",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "CA audit fees, legal fees, consultant fees, labour law compliance costs",
  },
  {
    account_code:    "5340",
    account_name:    "GST Expense (Reverse Charge)",
    account_type:    "Expense",
    account_subtype: "Financial Expense",
    normal_balance:  "Dr",
    parent_code:     "5300",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    tax_type:        "CGST_Output",
    is_system:       true,
    description:     "GST payable under Reverse Charge Mechanism on certain exempt/imported services",
  },

  // ── Depreciation ─────────────────────────────────────────────────────────
  {
    account_code:    "5400",
    account_name:    "Depreciation & Provisions",
    account_type:    "Expense",
    account_subtype: "Depreciation",
    normal_balance:  "Dr",
    parent_code:     "5000",
    level:           1,
    is_group:        true,
    is_posting_account: false,
    is_system:       true,
    description:     "Non-cash charges — depreciation on assets, bad debt provisions",
  },
  {
    account_code:    "5410",
    account_name:    "Depreciation — Plant & Machinery",
    account_type:    "Expense",
    account_subtype: "Depreciation",
    normal_balance:  "Dr",
    parent_code:     "5400",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Annual depreciation on construction machinery and equipment",
  },
  {
    account_code:    "5420",
    account_name:    "Depreciation — Vehicles",
    account_type:    "Expense",
    account_subtype: "Depreciation",
    normal_balance:  "Dr",
    parent_code:     "5400",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Annual depreciation on company-owned vehicles",
  },
  {
    account_code:    "5430",
    account_name:    "Provision for Bad & Doubtful Debts",
    account_type:    "Expense",
    account_subtype: "Depreciation",
    normal_balance:  "Dr",
    parent_code:     "5400",
    level:           2,
    is_group:        false,
    is_posting_account: true,
    is_system:       true,
    description:     "Provision created for receivables that may not be recoverable from clients",
  },
];

export default DEFAULT_ACCOUNTS;
