    item_id :"ABS001",
    item_name: "EARTH WORK", 
    n_rate: 199.90,
    n_amount: 202098,
    quantity: 1011,
    consumable_material_rate: MT_CM_rate,
    consumable_material_amount: quantity * MT_CM_rate,
    bulk_material_rate: MT_BL_rate,
    bulk_material_amount: quantity * MT_BL_rate,
    machinery_rate: MY_M_rate,
    machinery_amount: quantity * MY_M_rate,
    fuel_rate: MY_F_rate,
    fuel_amount: quantity * MY_F_rate,
    contractor_rate: MP_C_rate,
    contractor_amount: quantity * MP_C_rate,
    nmr_rate: MP_NMR_rate,
    nmr_amount: quantity * MP_NMR_rate,
    final_rate: final_rate,
    final_amount: quantity * final_rate,
    variance_amount: final_amount - n_amount,
    variance_percentage: (final_amount - n_amount) / n_amount * 100,


        boq_total_amount: sum of all n_amount,
    zero_cost_total_amount: sum of all final_amount,
    variance_amount: sum of all variance_amount,
    variance_percentage: sum of all variance_percentage,
    consumable_material: sum of all consumable_material_amount,
    bulk_material: sum of all bulk_material_amount,
    total_material_amount: sum of all total_material_amount,
    machinery: sum of all machinery_amount,
    fuel: sum of all fuel_amount,
    total_machine_amount: sum of all total_machine_amount,
    contractor: sum of all contractor_amount,
    nmr: sum of all nmr_amount,
    total_labor_amount: sum of all total_labor_amount,